import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";
import { Container, Header } from "@/styles/pages/app";
import { Roboto } from "next/font/google";
import Image from "next/image";

import logoImg from "@/assets/logo.svg";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

globalStyles();
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={roboto.className}>
        <Container>
          <Header>
            <Image src={logoImg} alt="Logo Ignite Shop" />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  );
}
